database_data_acess:
    resource: "@DatabaseDataAcessBundle/Resources/config/routing.yml"
    prefix:   /

resource_equipment:
    resource: "@ResourceEquipmentBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
