resource_equipment_homepage:
    path:     /
    defaults: { _controller: ResourceEquipmentBundle:Default:index }

resource_equipment_add:
    path:     /addEquip
    defaults: { _controller: ResourceEquipmentBundle:Form:add }
resource_equipment_addtoDB:
    path:     /add
    defaults: { _controller: ResourceEquipmentBundle:Form:saveEquipment }
